apiVersion: apps/v1
kind: Deployment
metadata:
  name: medplum-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: medplum-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: medplum-backend
  template:
    metadata:
      labels:
        app: medplum-backend
    spec:
      containers:
        - name: medplum-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 8103
          env:
            {{- range .Values.backend.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: MEDPLUM_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: medplum-db-secret
                  key: db-password
            - name: MEDPLUM_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: medplum-redis-secret
                  key: redis-password
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}