{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: medplum-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: medplum-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
{{- end }}