apiVersion: v1
kind: Secret
metadata:
  name: medplum-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: medplum-redis-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}