apiVersion: v1
kind: Service
metadata:
  name: {{ include "medplum.fullname" . }}-service
  namespace: {{ include "medplum.namespace" . }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 8103 }}
  selector:
    {{- include "medplum.selectorLabels" . | nindent 4 }}